//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftRegister.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftEntertainment
    {
        public int GiftId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string NameOfEmployee { get; set; }
        public Nullable<System.DateTime> DateGiftWasReceived { get; set; }
        public string GiftReceivedFrom { get; set; }
        public string DescriptionOfGiftReceived { get; set; }
        public Nullable<System.DateTime> DateGiftWasGiven { get; set; }
        public string GiftGivenTo { get; set; }
        public string DescriptionOfGiftGiven { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
    }
}
